### ISSUE TITLE
can you consider making a bug fix for turret ai?

### ISSUE THREAD

**Issue by po456asd** [ToyDragon/ROR2ModEngineerLunarCoinFix#1]
i love your fix on this so far but i wonder if you can make a fix for turret ai too.

**Comment by po456asd** [comment]
also Install UMM make game build goes from number to just "MOD"

**Comment by ToyDragon** [comment]
Thanks bud that's a great idea, I'll look into it. You get put into MOD mode when you enable the cheating mods, you can disable them in UMM to be put back in normal mode.

**Comment by po456asd** [comment]
i didn't install any cheat mod. i just want your fix to my game.
![image](https://user-images.githubusercontent.com/13596788/55924694-18c38680-5c35-11e9-8c7e-ad034e3d0e6c.png)
![image](https://user-images.githubusercontent.com/13596788/55924701-24af4880-5c35-11e9-9f64-3beec0d58642.png)

in picture i uninstall UMM to play normally because if i install my game will go MOD mode.

even install just UMM without any mod the game will still change into MOD mode

**Comment by po456asd** [comment]
Video : https://youtu.be/OyXyZbZxw2c
i just fresh install game then install UMM without any mod and game still flagged as MOD

**Comment by ToyDragon** [comment]
https://github.com/newman55/unity-mod-manager/issues/21#issuecomment-481664439

Ew gross, it looks like on UMMs side they always set the mod flag in the latest version. I'll try to come up with a solution.

**Comment by po456asd** [comment]
UMM 0.16.0 is working. it not force to flag a game to MOD, but 0.16.1 are.
another question for qol. if i got dll of mod how can i know what to write in Info.json?
in this case i want to try https://github.com/ontrigger/ItemStatsMod

**Comment by ToyDragon** [comment]
Moved off of UMM, forgot to update this issue.
